name: CI Pipeline

on:
  push:
    branches:
      - main  # Déclenche le workflow sur chaque push sur la branche 'main'
  pull_request:
    branches:
      - main  # Déclenche aussi sur les pull requests vers la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3  # Version mise à jour

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4  # Version mise à jour
        with:
          python-version: '3.12'  # Version Python utilisée

      # Étape 3 : Installer Poetry et les dépendances
      - name: Install Poetry and dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --no-root  # Évite d'installer le projet en tant que package

      # Étape 4 : Lancer les tests avec couverture
      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=app --cov-report=term-missing

      # Étape 5 : Vérification du formatage avec Black
      - name: Check PEP8 compliance with Black
        run: |
          poetry run black --check .

      # Étape 6 : Vérification des types avec MyPy
      - name: Type checking with MyPy
        run: |
          poetry run mypy app/
